import { Church, Mountain, Car, Bed, Users, Camera } from "lucide-react";

// Tourism data for Amhara region
export const searchData = [
  // UNESCO World Heritage Sites
  {
    id: 1,
    name: "Lalibela Rock-Hewn Churches",
    type: "UNESCO World Heritage Site",
    location: "Lalibela",
    description:
      "11 remarkable rock-hewn churches carved directly into volcanic rock, representing one of the most extraordinary religious sites in the world.",
    image: "/images/amhara/lalibela-1-min.jpg",
    rating: 4.9,
    reviews: 2847,
    price: "Free",
    duration: "4-6 hours",
    category: "heritage",
    prodtype: "attraction",
    icon: Church,
    features: ["UNESCO Site", "Guided Tours", "Photography"],
    languages: ["English", "Amharic", "French"],
    accessibility: true,
    activities: [
      { name: "Guided Church Tour", price: "$15", duration: "3 hours" },
      { name: "Photography Workshop", price: "$35", duration: "4 hours" },
      { name: "Cultural Performance", price: "$20", duration: "2 hours" },
    ],
    gallery: [
      "/images/amhara/lalibela-1-min.jpg",
      "/images/amhara/Gondar-1.jpg",
      "/images/amhara/MG_7474-2048x1365.jpg",
    ],
  },
  {
    id: 2,
    name: "Fasil Ghebbi - Gondar Castles",
    type: "Royal Enclosure",
    location: "Gondar",
    description:
      "The 'Camelot of Africa' - a fortress-city containing six castles and several other buildings, showcasing 17th-century Ethiopian architecture.",
    image: "/images/amhara/Gondar-1.jpg",
    rating: 4.8,
    reviews: 1923,
    price: "150 ETB",
    duration: "3-4 hours",
    category: "heritage",
    prodtype: "attraction",
    icon: Church,
    features: ["Historical Site", "Architecture", "Photography"],
    languages: ["English", "Amharic"],
    accessibility: false,
    activities: [
      { name: "Castle Tour", price: "$12", duration: "2 hours" },
      { name: "Historical Photography", price: "$25", duration: "3 hours" },
    ],
    gallery: [
      "/images/amhara/Gondar-1.jpg",
      "/images/amhara/lalibela-1-min.jpg",
      "/images/amhara/DJI_0087.jpg",
    ],
  },
  // National Parks
  {
    id: 3,
    name: "Simien Mountains National Park",
    type: "National Park",
    location: "Simien Mountains",
    description:
      "UNESCO World Heritage park famous for its dramatic highland scenery, endemic Gelada baboons, and challenging trekking routes.",
    image: "/images/amhara/semien-mountains.png",
    rating: 4.9,
    reviews: 1456,
    price: "300 ETB",
    duration: "1-7 days",
    category: "nature",
    prodtype: "trekking",
    icon: Mountain,
    features: ["Wildlife", "Trekking", "Camping", "UNESCO Site"],
    languages: ["English", "Amharic"],
    accessibility: false,
    activities: [
      { name: "Gelada Baboon Watching", price: "$40", duration: "Half day" },
      { name: "Multi-day Trekking", price: "$200", duration: "3-7 days" },
      { name: "Wildlife Photography", price: "$60", duration: "Full day" },
    ],
    gallery: [
      "/images/amhara/semien-mountains.png",
      "/images/amhara/MG_7474-2048x1365.jpg",
      "/images/amhara/DJI_0087.jpg",
    ],
  },
  // Activities
  {
    id: 4,
    name: "Lake Tana Monastery Tour",
    type: "Boat Tour",
    location: "Bahir Dar",
    description:
      "Visit ancient monasteries on Lake Tana islands, source of the Blue Nile, with traditional papyrus boats and historic churches.",
    image: "/images/amhara/lake-tana.png",
    rating: 4.7,
    reviews: 892,
    price: "$45",
    duration: "6-8 hours",
    category: "cultural",
    prodtype: "tour",
    icon: Car,
    features: ["Boat Trip", "Monasteries", "History"],
    languages: ["English", "Amharic"],
    accessibility: true,
    activities: [
      { name: "Island Monastery Visit", price: "$35", duration: "4 hours" },
      {
        name: "Traditional Boat Experience",
        price: "$25",
        duration: "2 hours",
      },
    ],
    gallery: [
      "/images/amhara/lake-tana.png",
      "/images/amhara/DJI_0087.jpg",
      "/images/amhara/MG_7474-2048x1365.jpg",
    ],
  },
  {
    id: 5,
    name: "Blue Nile Falls Hiking",
    type: "Adventure Tour",
    location: "Bahir Dar",
    description:
      "Trek to the magnificent Blue Nile Falls (Tis Issat), known as 'Smoking Water' - one of Ethiopia's most spectacular waterfalls.",
    image: "/images/amhara/blue-nile-falls.png",
    rating: 4.8,
    reviews: 567,
    price: "$35",
    duration: "4-5 hours",
    category: "adventure",
    prodtype: "hiking",
    icon: Mountain,
    features: ["Waterfall", "Hiking", "Nature"],
    languages: ["English", "Amharic"],
    accessibility: false,
    activities: [
      { name: "Falls Hiking", price: "$25", duration: "3 hours" },
      { name: "Photography Tour", price: "$40", duration: "4 hours" },
    ],
    gallery: [
      "/images/amhara/blue-nile-falls.png",
      "/images/amhara/lake-tana.png",
      "/images/amhara/semien-mountains.png",
    ],
  },
  // Accommodation options
  {
    id: 6,
    name: "Kuriftu Resort & Spa",
    type: "Luxury Lake Resort",
    location: "Bahir Dar",
    description:
      "Premium Ethiopian resort chain with locations in Bahir Dar and other major cities. Experience luxury accommodation with locally-produced artworks and traditional Ethiopian hospitality.",
    image:
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.6,
    reviews: 834,
    price: "$120/night",
    duration: "Overnight",
    category: "luxury",
    prodtype: "accommodation",
    icon: Bed,
    features: [
      "Spa",
      "Lake View",
      "Restaurant",
      "Wifi",
      "Pool",
      "Conference Rooms",
    ],
    languages: ["English", "Amharic"],
    accessibility: true,
    rooms: 89,
    amenities: [
      "24/7 Room Service",
      "Fitness Center",
      "Business Center",
      "Free WiFi",
      "Laundry Service",
    ],
    checkIn: "2:00 PM",
    checkOut: "12:00 PM",
    roomTypes: [
      { name: "Standard Lake View", price: "$120", capacity: 2 },
      { name: "Deluxe Suite", price: "$180", capacity: 4 },
      { name: "Presidential Suite", price: "$350", capacity: 6 },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?q=80&w=1932&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "/images/amhara/lake-tana.png",
      "/images/amhara/MG_7474-2048x1365.jpg",
    ],
  },
  {
    id: 7,
    name: "Avanti Blue Nile Resort",
    type: "4-Star Hotel",
    location: "Bahir Dar",
    description:
      "135 rooms with all modern amenities, located on Lake Tana with views of the lake. Away from the main road with private entrance.",
    image: "/images/amhara/MG_7474-2048x1365.jpg",
    rating: 4.4,
    reviews: 623,
    price: "$85/night",
    duration: "Overnight",
    category: "mid-range",
    prodtype: "accommodation",
    icon: Bed,
    features: ["Lake View", "Restaurant", "Wifi", "Parking", "Bar", "Garden"],
    languages: ["English", "Amharic"],
    accessibility: true,
    rooms: 135,
    amenities: [
      "Restaurant",
      "Bar",
      "Free Parking",
      "Garden",
      "Terrace",
      "Airport Shuttle",
    ],
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    roomTypes: [
      { name: "Standard Room", price: "$85", capacity: 2 },
      { name: "Lake View Suite", price: "$120", capacity: 3 },
    ],
    gallery: [
      "/images/amhara/MG_7474-2048x1365.jpg",
      "/images/amhara/DJI_0087.jpg",
      "/images/amhara/lake-tana.png",
    ],
  },
  {
    id: 8,
    name: "Lal Hotel Lalibela",
    type: "Heritage Hotel",
    location: "Lalibela",
    description:
      "Large hotel set in spacious grounds on the outskirts of Lalibela. 100 en-suite rooms designed to suit the architecture of Lalibela.",
    image: "/images/amhara/lalibela-1-min.jpg",
    rating: 4.3,
    reviews: 445,
    price: "$95/night",
    duration: "Overnight",
    category: "mid-range",
    prodtype: "accommodation",
    icon: Bed,
    features: [
      "Traditional Architecture",
      "Restaurant",
      "Garden",
      "Conference Room",
    ],
    languages: ["English", "Amharic"],
    accessibility: false,
    rooms: 100,
    amenities: [
      "Restaurant",
      "Garden",
      "Conference Facilities",
      "Traditional Decor",
      "Tour Desk",
    ],
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    roomTypes: [
      { name: "Traditional Room", price: "$95", capacity: 2 },
      { name: "Heritage Suite", price: "$140", capacity: 4 },
    ],
    gallery: [
      "/images/amhara/lalibela-1-min.jpg",
      "/images/amhara/Gondar-1.jpg",
      "/images/amhara/DJI_0087.jpg",
    ],
  },
  {
    id: 9,
    name: "Goha Hotel",
    type: "Hill-Top Hotel",
    location: "Gondar",
    description:
      "Ideally situated on the hills of the city and a short distance away from the medieval castles with panoramic views.",
    image: "/images/amhara/Gondar-1.jpg",
    rating: 4.2,
    reviews: 356,
    price: "$70/night",
    duration: "Overnight",
    category: "mid-range",
    prodtype: "accommodation",
    icon: Bed,
    features: [
      "City View",
      "Restaurant",
      "Historical Location",
      "Panoramic Views",
    ],
    languages: ["English", "Amharic"],
    accessibility: true,
    rooms: 65,
    amenities: [
      "Restaurant",
      "Bar",
      "City Views",
      "Historical Tours",
      "Free WiFi",
    ],
    checkIn: "2:00 PM",
    checkOut: "12:00 PM",
    roomTypes: [
      { name: "Standard City View", price: "$70", capacity: 2 },
      { name: "Panoramic Suite", price: "$110", capacity: 3 },
    ],
    gallery: [
      "/images/amhara/Gondar-1.jpg",
      "/images/amhara/MG_7474-2048x1365.jpg",
      "/images/amhara/DJI_0087.jpg",
    ],
  },
  // Adventure activities
  {
    id: 10,
    name: "Horseback Riding Experience",
    type: "Cultural Activity",
    location: "Amhara Region",
    description:
      "Experience traditional horseback riding with decorated horses, attending annual galloping events - a lifetime experience in Amhara.",
    image: "/images/amhara/MG_7474-2048x1365.jpg",
    rating: 4.5,
    reviews: 234,
    price: "$40",
    duration: "3-4 hours",
    category: "cultural",
    prodtype: "activity",
    icon: Mountain,
    features: ["Traditional Culture", "Horse Riding"],
    languages: ["English", "Amharic"],
    accessibility: false,
    activities: [
      { name: "Traditional Horse Riding", price: "$30", duration: "2 hours" },
      {
        name: "Cultural Festival Experience",
        price: "$50",
        duration: "Full day",
      },
    ],
    gallery: [
      "/images/amhara/MG_7474-2048x1365.jpg",
      "/images/amhara/DJI_0087.jpg",
      "/images/amhara/semien-mountains.png",
    ],
  },
  {
    id: 11,
    name: "Community Tourism Experience",
    type: "Community Tour",
    location: "Various Locations",
    description:
      "Visit TESFA community guesthouses, Aweramba community, and Menz Guassa conservation area for authentic cultural experiences.",
    image: "/images/amhara/DJI_0087.jpg",
    rating: 4.7,
    reviews: 189,
    price: "$65",
    duration: "1-2 days",
    category: "cultural",
    prodtype: "community",
    icon: Users,
    features: ["Community Tourism", "Authentic Culture", "Local Stay"],
    languages: ["English", "Amharic"],
    accessibility: true,
    activities: [
      { name: "Community Homestay", price: "$45", duration: "Overnight" },
      { name: "Traditional Craft Workshop", price: "$25", duration: "3 hours" },
    ],
    gallery: [
      "/images/amhara/DJI_0087.jpg",
      "/images/amhara/lalibela-1-min.jpg",
      "/images/amhara/Gondar-1.jpg",
    ],
  },
  {
    id: 12,
    name: "Bird Watching Tour",
    type: "Wildlife Experience",
    location: "Simien Mountains",
    description:
      "Host some of the rare and endemic bird species like Lammergeyer and Ankober Serin. Perfect for serious birding enthusiasts.",
    image: "/images/amhara/semien-mountains.png",
    rating: 4.6,
    reviews: 287,
    price: "$55",
    duration: "6-8 hours",
    category: "nature",
    prodtype: "wildlife",
    icon: Camera,
    features: ["Endemic Species", "Wildlife", "Photography"],
    languages: ["English", "Amharic"],
    accessibility: false,
    activities: [
      { name: "Endemic Bird Watching", price: "$45", duration: "4 hours" },
      { name: "Wildlife Photography", price: "$65", duration: "Full day" },
    ],
    gallery: [
      "/images/amhara/semien-mountains.png",
      "/images/amhara/MG_7474-2048x1365.jpg",
      "/images/amhara/DJI_0087.jpg",
    ],
  },
  // Additional Hotels
  {
    id: 13,
    name: "Fasil Lodge",
    type: "Historic Lodge",
    location: "Gondar",
    description:
      "Historic lodge located in the heart of Gondar, walking distance to Fasilides Castle and the Royal Enclosure. Traditional Ethiopian architecture with modern amenities.",
    image: "/images/amhara/Gondar-1.jpg",
    rating: 4.1,
    reviews: 298,
    price: "$60/night",
    duration: "Overnight",
    category: "budget",
    prodtype: "accommodation",
    icon: Bed,
    features: [
      "Historic Location",
      "Walking Distance to Castles",
      "Traditional Decor",
      "Restaurant",
    ],
    languages: ["English", "Amharic"],
    accessibility: true,
    rooms: 45,
    amenities: [
      "Restaurant",
      "Traditional Architecture",
      "Tour Guidance",
      "Cultural Shows",
      "Free Parking",
    ],
    checkIn: "1:00 PM",
    checkOut: "11:00 AM",
    roomTypes: [
      { name: "Standard Historic Room", price: "$60", capacity: 2 },
      { name: "Traditional Suite", price: "$90", capacity: 3 },
    ],
    gallery: [
      "/images/amhara/Gondar-1.jpg",
      "/images/amhara/lalibela-1-min.jpg",
      "/images/amhara/MG_7474-2048x1365.jpg",
    ],
  },
  {
    id: 14,
    name: "Tana Hotel",
    type: "Lakeside Hotel",
    location: "Bahir Dar",
    description:
      "Located on the shores of Lake Tana, offering stunning lake views and easy access to island monasteries. Popular with both business and leisure travelers.",
    image: "/images/amhara/lake-tana.png",
    rating: 4.0,
    reviews: 512,
    price: "$75/night",
    duration: "Overnight",
    category: "mid-range",
    prodtype: "accommodation",
    icon: Bed,
    features: ["Lake Views", "Boat Access", "Business Center", "Restaurant"],
    languages: ["English", "Amharic"],
    accessibility: true,
    rooms: 78,
    amenities: [
      "Lake Views",
      "Restaurant",
      "Bar",
      "Business Center",
      "Boat Trips",
      "Conference Rooms",
    ],
    checkIn: "2:00 PM",
    checkOut: "12:00 PM",
    roomTypes: [
      { name: "Lake View Room", price: "$75", capacity: 2 },
      { name: "Business Suite", price: "$105", capacity: 3 },
    ],
    gallery: [
      "/images/amhara/lake-tana.png",
      "/images/amhara/DJI_0087.jpg",
      "/images/amhara/MG_7474-2048x1365.jpg",
    ],
  },
  {
    id: 15,
    name: "Maribela Hotel",
    type: "Mountain Lodge",
    location: "Lalibela",
    description:
      "Cozy mountain lodge with authentic Ethiopian hospitality. Features traditional tukul-style rooms and spectacular mountain views. Perfect for pilgrims and culture enthusiasts.",
    image: "/images/amhara/lalibela-1-min.jpg",
    rating: 4.3,
    reviews: 187,
    price: "$80/night",
    duration: "Overnight",
    category: "mid-range",
    prodtype: "accommodation",
    icon: Bed,
    features: [
      "Mountain Views",
      "Traditional Tukul Rooms",
      "Cultural Experience",
      "Restaurant",
    ],
    languages: ["English", "Amharic"],
    accessibility: false,
    rooms: 32,
    amenities: [
      "Traditional Architecture",
      "Mountain Views",
      "Cultural Programs",
      "Restaurant",
      "Hiking Guides",
    ],
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    roomTypes: [
      { name: "Traditional Tukul", price: "$80", capacity: 2 },
      { name: "Mountain View Suite", price: "$115", capacity: 3 },
    ],
    gallery: [
      "/images/amhara/lalibela-1-min.jpg",
      "/images/amhara/Gondar-1.jpg",
      "/images/amhara/semien-mountains.png",
    ],
  },
  {
    id: 16,
    name: "Simien Lodge",
    type: "Eco Lodge",
    location: "Simien Mountains",
    description:
      "Africa's highest lodge at 3,200m altitude. Eco-friendly accommodation with breathtaking views of the Simien escarpment. Perfect base for trekking and wildlife viewing.",
    image: "/images/amhara/semien-mountains.png",
    rating: 4.5,
    reviews: 156,
    price: "$110/night",
    duration: "Overnight",
    category: "luxury",
    prodtype: "accommodation",
    icon: Bed,
    features: [
      "Highest Lodge in Africa",
      "Eco-Friendly",
      "Wildlife Viewing",
      "Trekking Base",
    ],
    languages: ["English", "Amharic"],
    accessibility: false,
    rooms: 20,
    amenities: [
      "Eco-Friendly",
      "Wildlife Viewing",
      "Trekking Guides",
      "Restaurant",
      "Panoramic Views",
    ],
    checkIn: "2:00 PM",
    checkOut: "11:00 AM",
    roomTypes: [
      { name: "Eco Room", price: "$110", capacity: 2 },
      { name: "Summit Suite", price: "$165", capacity: 3 },
    ],
    gallery: [
      "/images/amhara/semien-mountains.png",
      "/images/amhara/MG_7474-2048x1365.jpg",
      "/images/amhara/DJI_0087.jpg",
    ],
  },
];

// Currency conversion rates (ETB to USD)
export const ETB_TO_USD_RATE = 0.018; // 1 ETB = ~0.018 USD
export const USD_TO_ETB_RATE = 55.5; // 1 USD = ~55.5 ETB
